export enum DocumentType {
    DRIVERS_LICENSE = 'DRIVERS_LICENSE',
    VEHICLE_REGISTRATION = 'VEHICLE_REGISTRATION',
    INSURANCE = 'INSURANCE',
    PROFILE_PHOTO = 'PROFILE_PHOTO',
    VEHICLE_PHOTO = 'VEHICLE_PHOTO',
    BACKGROUND_CHECK = 'BACKGROUND_CHECK',
}
