export enum NotificationType {
    RIDE_REQUEST = 'RIDE_REQUEST',
    RIDE_ACCEPTED = 'RIDE_ACCEPTED',
    PAYMENT = 'PAYMENT',
    PROMO = 'PROMO',
    SYSTEM = 'SYSTEM',
    CHAT_MESSAGE = 'CHAT_MESSAGE',
    WALLET_FUNDED = 'WALLET_FUNDED',
    WITHDRAWAL_UPDATE = 'WITHDRAWAL_UPDATE',
}