export enum TicketCategory {
    RIDE_ISSUE = 'RIDE_ISSUE',
    PAYMENT_ISSUE = 'PAYMENT_ISSUE',
    DRIVER_BEHAVIOR = 'DRIVER_BEHAVIOR',
    RIDER_BEHAVIOR = 'RIDER_BEHAVIOR',
    VEHICLE_ISSUE = 'VEHICLE_ISSUE',
    ACCOUNT_ISSUE = 'ACCOUNT_ISSUE',
    TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',
    REFUND_REQUEST = 'REFUND_REQUEST',
    GENERAL_INQUIRY = 'GENERAL_INQUIRY',
    OTHER = 'OTHER',
}
